### ISSUE TITLE
Broken standings page

### ISSUE THREAD

**Issue by Absotively** [muyjohno/cobra#104]
I see an error when attempting to view [the standings page for yesterday’s regional in Calgary](http://cobr.ai/tournaments/1065/players/standings).

**Comment by Absotively** [comment]
Just noticed the pairings tab has three extra "Double Elim" headers, which seems like it might be related.

**Comment by muyjohno** [comment]
Thanks for the report, and sorry for the silence. Occasionally this happens when multiple stages are created, as you described, and weird things start happening. Since the event is so old now, I don't plan to do a great deal for it, but I did clean it up a little so at least it won't error. Some tweaks have been made to hopefully make the flow easier so strange things like this are less likely to happen. I'm going to close this now in the name of clearing up github issues.
