### ISSUE TITLE
Feature Request: JSON API

### ISSUE THREAD

**Issue by dodgepong** [muyjohno/cobra#89]
It could be really cool if Cobra had a JSON API. As a broadcaster, I could write an application that pulls down tournament data to display on screen, such as current standings, ID distribution, and win stats.

**Comment by muyjohno** [comment]
Thanks for the suggestion! Interestingly, this is an idea that I've had in the back of my mind for a while since I think it would be an amazing feature for just what you describe. I'm hoping to find some time to pick up development again in advance of regional season, so I may well come back to you on this for your thoughts on specific features.

**Comment by muyjohno** [comment]
Really basic implementation as of 1.1
